version: "3"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      HOST: ${HOSTNAME}
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/videosDB
      MAX_VIDEOS_PER_UPLOAD: 10
    depends_on:
      - mongo
volumes:
  mongo-data:
